stages:
  - start

start-job-main:
  stage: start
  script:
    - source ~/.venv/bin/activate
    - cp tomcat9/webapps/sso/liw-sso-token-receiver.jsp /var/lib/tomcat9/webapps/sso/liw-sso-token-receiver.jsp
    - bash stop.sh
    - exec nohup bash start.sh >/dev/null 2>&1 &
  variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG"
    GIT_STRATEGY: fetch
    GIT_CLEAN_FLAGS: -ffdx -e logs/ -e data/ -e .streamlit/ -e "*.json" -e flask_session/
  when: on_success
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

start-job-dev:
  stage: start
  script:
    - source ~/.venv/bin/activate
    - cp tomcat9/webapps/sso/liw-sso-token-receiver.jsp /var/lib/tomcat9/webapps/sso/liw-sso-token-receiver-dev.jsp
    - bash stop.dev.sh
    - exec nohup bash start.dev.sh >/dev/null 2>&1 &
  variables:
    GIT_CLONE_PATH: "$CI_BUILDS_DIR/$CI_PROJECT_PATH_SLUG/$CI_COMMIT_REF_SLUG"
    GIT_STRATEGY: fetch
    GIT_CLEAN_FLAGS: -ffdx -e logs/ -e data/ -e .streamlit/ -e "*.json" -e flask_session/
  when: on_success
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'

 