"""
Order 쿼리 (M_SO_LINE) - KPI / Raw
active_orders.html 전용 쿼리는 queries/active_orders_queries.py 에 분리됨
"""
import os

QUERY_ORDER_KPI = """
-- 주문 KPI
WITH T_CURRENCY AS (
    SELECT A.P_PTT, A.FROM_CURRENCY_CODE,
           CASE WHEN B.USD_CONVERSION_RATE <> 0
                THEN A.USD_CONVERSION_RATE / B.USD_CONVERSION_RATE END AS CONVERSION_RATE
      FROM `pjt-lge-oversea-sales-olap`.SCM_OLAP.D_USD_CONVERSION_RATE_MST A
      JOIN `pjt-lge-oversea-sales-olap`.SCM_OLAP.D_USD_CONVERSION_RATE_MST B
        ON A.P_PTT = B.P_PTT AND B.FROM_CURRENCY_CODE = @currency
     WHERE A.P_PTT >= @start_date AND @currency != 'USD'
    UNION ALL
    SELECT A.P_PTT, A.FROM_CURRENCY_CODE, A.USD_CONVERSION_RATE AS CONVERSION_RATE
      FROM `pjt-lge-oversea-sales-olap`.SCM_OLAP.D_USD_CONVERSION_RATE_MST A
     WHERE A.P_PTT >= @start_date AND @currency = 'USD'
)
SELECT
  COUNT(*) AS total_lines,
  COUNTIF(LINE_STATUS_CODE IN ('CLOSED','Completed')) AS closed_lines,
  COUNTIF(LINE_STATUS_CODE IN ('CLOSED','Completed') AND ACTUAL_SHIPMENT_DATE IS NOT NULL AND RAD_DATE IS NOT NULL AND ACTUAL_SHIPMENT_DATE <= DATE(RAD_DATE)) AS ontime_lines,
  COUNTIF(LINE_STATUS_CODE IN ('CLOSED','Completed') AND ACTUAL_SHIPMENT_DATE IS NOT NULL AND RAD_DATE IS NOT NULL AND ACTUAL_SHIPMENT_DATE > DATE(RAD_DATE)) AS delayed_lines,
  COUNTIF(BACK_ORDER_HOLD = 'Y') AS backorder_lines,
  COUNTIF(INIT_PROMISED_ARRIVAL_DATE IS NOT NULL AND PROMISED_ARRIVAL_DATE IS NOT NULL AND INIT_PROMISED_ARRIVAL_DATE != DATE(PROMISED_ARRIVAL_DATE)) AS rescheduled_lines,
  COUNTIF(LINE_STATUS_CODE IN ('CANCELLED','Fully Cancelled')) AS cancelled_lines,
  ROUND(AVG(CASE WHEN LINE_STATUS_CODE IN ('CLOSED','Completed') AND ACTUAL_SHIPMENT_DATE IS NOT NULL AND ORDERED_DATE IS NOT NULL THEN DATE_DIFF(ACTUAL_SHIPMENT_DATE, ORDERED_DATE, DAY) END), 1) AS avg_lead_time_days,
  COUNTIF(LINE_STATUS_CODE IN ('CLOSED','Completed') AND (ACTUAL_SHIPMENT_DATE IS NULL OR RAD_DATE IS NULL)) AS closed_no_rad_lines,
  COUNTIF(LINE_STATUS_CODE NOT IN ('CANCELLED','CLOSED','Fully Cancelled','Completed')) AS open_lines,
  COUNTIF(LINE_STATUS_CODE = 'ENTERED') AS entered_lines,
  COUNTIF(LINE_STATUS_CODE IN ('BOOKED','AWAITING_RECEIPT','AWAITING_FULFILLMENT','AWAITING_SHIPPING','PICKED_PARTIAL') AND PICK_RELEASE_DATE IS NULL) AS booked_lines,
  COUNTIF(LINE_STATUS_CODE IN ('BOOKED','AWAITING_RECEIPT','AWAITING_FULFILLMENT','AWAITING_SHIPPING','PICKED_PARTIAL') AND PICK_RELEASE_DATE IS NOT NULL) AS pick_release_lines,
  COUNTIF(LINE_STATUS_CODE IN ('PICKED','FULFILLED')) AS picked_lines,
  COUNTIF(LINE_STATUS_CODE IN ('SHIPPED','INVOICED','INVOICE_HOLD','PRE-BILLING_ACCEPTANCE','INVOICE_NOT_APPLICABLE','Fully Shipped')) AS shipped_lines,
  ROUND(SUM(COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT)), 0) AS total_usd,
  ROUND(SUM(CASE WHEN LINE_STATUS_CODE IN ('CLOSED','Completed') THEN COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT) END), 0) AS closed_usd,
  ROUND(SUM(CASE WHEN LINE_STATUS_CODE NOT IN ('CANCELLED','CLOSED','Completed','Fully Cancelled') THEN COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT) END), 0) AS open_usd,
  ROUND(SUM(CASE WHEN BACK_ORDER_HOLD = 'Y' THEN COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT) END), 0) AS backorder_usd,
  ROUND(SUM(CASE WHEN LINE_STATUS_CODE IN ('CANCELLED','Fully Cancelled') THEN COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT) END), 0) AS cancelled_usd,
  ROUND(SUM(CASE WHEN INIT_PROMISED_ARRIVAL_DATE IS NOT NULL AND PROMISED_ARRIVAL_DATE IS NOT NULL AND INIT_PROMISED_ARRIVAL_DATE != DATE(PROMISED_ARRIVAL_DATE) THEN COALESCE(T.ORDER_AMOUNT * CR.CONVERSION_RATE, T.USD_ORDER_AMOUNT) END), 0) AS rescheduled_usd
FROM `pjt-lge-oversea-sales-olap`.SCM_OLAP.M_SO_LINE T
LEFT JOIN T_CURRENCY CR ON T.ORDERED_DATE = CR.P_PTT AND T.CURRENCY_CODE = CR.FROM_CURRENCY_CODE
WHERE ORDERED_DATE >= @start_date
  AND ORDERED_DATE < @end_date
  AND (@legal_entity = 'ALL' OR SUBSDR_NAME = @legal_entity)
  AND (@division = '[ALL]' OR DIV_NM = @division)
"""

QUERY_ORDER_RAW = """
-- Raw 주문 라인 데이터 (AG Grid)
SELECT
  AFFILIATE_CODE, SUBSDR_NAME, T.DIV_NM,
  SALES_ORDER_NO, SALES_ORDER_LINE_NO, ORDER_LINE_ID,
  ORDER_TYPE_NAME, PICK_NO, CUST_PO_NO,
  ORDER_STATUS_CODE, LINE_STATUS_CODE, LINE_CATEGORY_CODE, ORDER_CATEGORY_CODE,
  CUSTOMER_CODE, CUSTOMER_NAME,
  MODEL_CODE, MODEL_CATEGORY, PRODUCT_LEVEL1_CODE, PRODUCT_LEVEL2_CODE,
  M.PROD_LVL1_NM AS PRODUCT_LEVEL1_NAME,
  M.PROD_LVL2_NM AS PRODUCT_LEVEL2_NAME,
  M.PROD_LVL3_NM AS PRODUCT_LEVEL3_NAME,
  M.PROD_LVL4_NM AS PRODUCT_LEVEL4_NAME,
  ORDERED_DATE, BOOKED_DATE, CUST_PO_DATE,
  REQUEST_SHIPPING_DATE, PICK_RELEASE_DATE, PICKING_DATE, PROMISED_SHIP_DATE,
  ACTUAL_SHIPMENT_DATE, SALES_DATE,
  DATE(RAD_DATE) AS RAD_DATE,
  REQUEST_ARRIVAL_FROM_DATE, REQUEST_ARRIVAL_TO_DATE,
  DATE(PROMISED_ARRIVAL_DATE) AS promised_arrival_date,
  INIT_PROMISED_ARRIVAL_DATE,
  DATE(COALESCE(TMS_APPOINTMENT_FROM_DATE, APPOINTMENT_FROM_DATE)) AS appointment_from_date,
  DATE(COALESCE(TMS_APPOINTMENT_TO_DATE, APPOINTMENT_TO_DATE)) AS appointment_to_date,
  ORDER_QTY, CANCEL_QTY, OPEN_FLAG, HOLD_FLAG, HOLD_REASON_CODE, BACK_ORDER_HOLD,
  PICK_RELEASE_YN, WAREHOUSE_CODE, CURRENCY_CODE, UNIT_SELLING_PRICE,
  ORDER_AMOUNT, USD_ORDER_AMOUNT, SHIPPING_METHOD_CODE, SALESPERSON_NAME,
  ROUND(CASE WHEN LINE_STATUS_CODE = 'CLOSED' AND ACTUAL_SHIPMENT_DATE IS NOT NULL AND ORDERED_DATE IS NOT NULL THEN DATE_DIFF(ACTUAL_SHIPMENT_DATE, ORDERED_DATE, DAY) END, 1) AS lead_time_days,
  CASE WHEN INIT_PROMISED_ARRIVAL_DATE IS NOT NULL AND PROMISED_ARRIVAL_DATE IS NOT NULL AND INIT_PROMISED_ARRIVAL_DATE != DATE(PROMISED_ARRIVAL_DATE) THEN 'Y' ELSE 'N' END AS is_rescheduled,
  CASE WHEN OPEN_FLAG = 'Y' AND ACTUAL_SHIPMENT_DATE IS NULL AND LINE_STATUS_CODE NOT IN ('CANCELLED','CLOSED','Fully Cancelled','Completed') AND DATE(RAD_DATE) < CURRENT_DATE() THEN 'Y' ELSE NULL END AS risk_alert,
  CASE
    WHEN LINE_STATUS_CODE = 'ENTERED' THEN '100.Entered'
    WHEN LINE_STATUS_CODE IN ('BOOKED','AWAITING_RECEIPT','AWAITING_FULFILLMENT','AWAITING_SHIPPING','PICKED_PARTIAL') THEN
      CASE WHEN PICK_RELEASE_DATE IS NULL THEN '200.Booked' ELSE '300.Pick Release' END
    WHEN LINE_STATUS_CODE IN ('PICKED','FULFILLED') THEN '400.Picked'
    WHEN LINE_STATUS_CODE IN ('SHIPPED','INVOICED','INVOICE_HOLD','PRE-BILLING_ACCEPTANCE','INVOICE_NOT_APPLICABLE') THEN '500.Shipped'
    WHEN LINE_STATUS_CODE IN ('CLOSED','Completed') THEN
      CASE WHEN ACTUAL_SHIPMENT_DATE IS NOT NULL AND RAD_DATE IS NOT NULL
        THEN CASE WHEN ACTUAL_SHIPMENT_DATE <= DATE(RAD_DATE) THEN '900.Closed (On-Time)' ELSE '900.Closed (Delayed)' END
        ELSE '900.Closed (No RAD or No Shipment Date)'
      END
    WHEN LINE_STATUS_CODE IN ('CANCELLED','Fully Cancelled') THEN '999.Cancelled'
    ELSE LINE_STATUS_CODE
  END AS delivery_status
FROM `pjt-lge-oversea-sales-olap`.SCM_OLAP.M_SO_LINE T
LEFT JOIN `pjt-lge-oversea-sales-olap`.PRD_OLAP.D_NPT_MDL_NEW_MST M ON T.MODEL_CODE = M.MDL_SFFX_CD
WHERE ORDERED_DATE >= @start_date
  AND ORDERED_DATE < @end_date
  AND (@legal_entity = 'ALL' OR SUBSDR_NAME = @legal_entity)
  AND (@division = '[ALL]' OR T.DIV_NM = @division)
ORDER BY ORDERED_DATE DESC
LIMIT 500000
"""

_bq_project = os.getenv('PROJECT_ID', 'pjt-lge-oversea-sales-olap')
_bq_dataset = os.getenv('DATASET_ID', 'SCM_OLAP')
_BQ_OLD = '`pjt-lge-oversea-sales-olap`.SCM_OLAP'
_BQ_NEW = f'`{_bq_project}`.{_bq_dataset}'

if _BQ_OLD != _BQ_NEW:
    import sys as _sys
    _mod = _sys.modules[__name__]
    for _qname in [n for n in vars(_mod) if n.startswith('QUERY_')]:
        setattr(_mod, _qname, getattr(_mod, _qname).replace(_BQ_OLD, _BQ_NEW))