출하 Header	TB_GTM_SHIPMENT_TMS_S_IF
출하 Detail	TB_GTM_CONTAINER_TMS_S_IF
운송 Leg	LD_LEG_DETL_T
배차/Load	LD_LEG_T
예약/Appointment	TB_GTM_BOOKINGHISTORY
상태	STATUS_R, SHIPMENT_R
고객	TB_GTM_SHIPTO, TB_GTM_OBS_CUSTOMER
입고	TB_GTM_IOD
Due Date	TB_GTM_DUE_DATE_CALCㅉ
ERP 연계	TB_GTM_ORDERS_GERP_R_IF


select * from(
 select inner_temp.*, rownum as devonindex from  ( 
    SELECT
        	TO_CHAR(APPOINTMENT_REQ_DATE, 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_REQ_DATE
        , 	TO_CHAR(APPOINTMENT_FROM_DATE, 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_FROM_DATE
		,	TO_CHAR(APPOINTMENT_DATE, 'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_DATE
		,	APPPOINTMENT_REMARK
    ,  APPOINTMENT_STATUS
    ,  SHPM_NUM
    ,  GERP_ORDER_NO
    ,  GERP_PICK_NO
    ,  CUSTOMER_ORDER_NO
    ,  LD_LEG_ID
    ,  CARR_NAME
    ,  STATUS
    ,  SHIPMENT_STATUS
    ,  TO_SHPG_LOC_CD
    ,  TO_CTY_NAME
    ,  TO_PSTL_CD
    ,  SHIP_TO_ADDRESS
    ,  MODEL_SUFFIX
    ,  MODEL_DESCRIPTION
    ,  UNIT_WEIGHT
    ,  SHIP_QTY
    ,  SHIP_CONFIRM_QTY
    ,  TOTAL_CBM
    ,  TOTAL_WEIGHT
    ,  PICKING_REMARK
    ,  SHIPPING_REMARK
    ,  GERP_SHIPTO_CODE
    ,  REFERENCE_NO
    ,  HUB -- Hub 관련 컬럼 추가 20150507 이동현
    ,  BOOKING_METHOD -- LGEDG 관련 컬럼 추가 20150513 이동현
    ,  BOOKING_LIST_TYPE -- LGEDG 관련 컬럼 추가 20150513 이동현
    ,  CASE WHEN (SELECT COUNT(1) FROM TB_GTM_OBS_CUSTOMER O_CUST WHERE O_CUST.SHIPTO_CODE IN (GERP_SHIPTO_CODE) AND O_CUST.LEGAL_ENTITY_NAME = LEGAL_ENTITY_NAME) > 0 THEN EMAIL_ADDRESS2
            ELSE EMAIL_ADDRESS
           END AS EMAIL_ADDRESS -- LGEDG 관련 컬럼 추가 20150513 이동현 / C20210604_30847 - OBS 고객 이메일 관련 변경 20210611
    ,  SHIP_TO_SHORT_NAME -- LGEDG 관련 컬럼 추가 20150615 이동현
    ,  REQUEST_NAME
    ,  LD_LEG_DETL_ID
    ,  BOOKING_HISTORY_ORDER_TYPE
    ,  SHPM_ID
    ,  SHIPMENT_LEG -- Hub 관련 컬럼 추가 20150421 이동현  
    ,  (SELECT CODEMST.CD_NM           FROM TB_GTM_CODE_MST CODEMST
               WHERE CODEMST.CD_TYPE = 'CUSTOMER_TYPE'
                 AND CODEMST.CD = CUSTOMER_TYPE) AS CUSTOMER_TYPE
      ,  CUSTOMER_TYPE AS CUSTOMER_TYPE_CD 
    ,  TO_CHAR(REQUEST_ARRIVAL_DATE, 'YYYY-MM-DD HH24:MI:SS') AS REQUEST_ARRIVAL_DATE
    ,  TO_CHAR(PICK_RELEASE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS PICK_RELEASE_DATE
    ,  CARR_CD
    ,  SRVC_CD
    ,  EQMT_TYP
    ,  TRCTR_NUM
    ,  TO_CHAR(FC_GTM_GET_DATE_SYSTOLOC(FRM_SHPG_LOC_CD, CRTD_DTT), 'YYYY-MM-DD HH24:MI:SS') AS CRTD_DTT
    ,  TO_CHAR(RELEASE_TO_WH_DATE, 'YYYY-MM-DD HH24:MI:SS') AS RELEASE_TO_WH_DATE
    ,  TO_CHAR(CFMD_DTT, 'YYYY-MM-DD HH24:MI:SS') AS CFMD_DTT
    ,  TO_CHAR(ACTUAL_ARRIVAL_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ACTUAL_ARRIVAL_DATE
    ,  TO_CHAR(IOD_INPUT_DATE, 'YYYY-MM-DD HH24:MI:SS') AS IOD_INPUT_DATE
    ,  FRM_SHPG_LOC_CD
    ,  UNIT_CBM
    ,  UNIT_NET_PRICE
    ,  UNIT_SELLING_PRICE
    ,  ORI_QUANTITY
    ,  IRECEIPT_QTY
    ,  ZONE
    ,  TO_CHAR(RAD_FROM, 'YYYY-MM-DD HH24:MI:SS') AS RAD_FROM
    ,  TO_CHAR(RAD_TO, 'YYYY-MM-DD HH24:MI:SS') AS RAD_TO
    ,  BOOKING_NEED_FLAG_DG -- LGEDG 관련 컬럼 추가 20150421 이동현
    ,  HUB_LOAD_ID -- Hub 관련 컬럼 추가 20150507 이동현
    ,   CUSTOMER_MODEL_CODE -- 20150625 원송연  
    ,  TO_CHAR(APPOINTMENT_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ORI_APPOINTMENT_DATE
    ,   TO_CHAR(SYSDATE-30, 'YYYY-MM-DD HH24:MI:SS') AS FROM_APP_DATE
    ,   TO_CHAR(SYSDATE+60, 'YYYY-MM-DD HH24:MI:SS') AS TO_APP_DATE
    ,   PALLET_QTY            AS PALLET_QTY             --LGEFS PALLET QTY ADD 20151111 BJSONG 
    ,   LINEAR_METER          AS LINEAR_METER           --LGEFS LINEAR_METER ADD 20151209 BJSONG 
    ,   SHIPPING_METHOD       AS SHIPPING_METHOD        --LGEFS SHIPPING_METHOD_CODE 20151111 BJSONG
     ,   LEGAL_ENTITY_NAME     AS LEGAL_ENTITY_NAME      --LGEFS LEGAL_ENTITY_NAME 20151111 BJSONG
     ,   RAD_FLAG -- [C20160325_20827] 컬럼 추가.
    ,   GERP_ORDER_LINE_NO --[C20171213_55962] Add Column
        ,  ORDER_TYPE      
      ,  TO_CHAR(ORDER_ENTRY_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ORDER_ENTRY_DATE
      ,  TRLR_NUM
      ,  TRCTR_LIC_NUM    
      ,  TO_CHAR(RFRC_NUM1, 'YYYY-MM-DD HH24:MI:SS') AS RFRC_NUM1
      ,  BOOKING_NEED_YN
      ,  FRM_SHPG_LOC_NAME
      ,  TO_SHPG_LOC_NAME      
      ,  TO_STA_CD
      ,  SHIP_TO_ZONE
      ,  DECODE(DISTANCE_USE_FLAG, 'Y', DISTANCE_LEAD_TIME, LEAD_TIME) AS LEAD_TIME
      ,  PL1
      ,  PL4
      ,  SUB_INVENTORY_CODE
      ,  TAX_PER_UNIT
      ,  FREIGHT_TERM
      ,  ZONE_NAME
      ,  SHRT_DESC
      ,  DECODE(BOOKING_NEED_YN, 'N', 'Y', DECODE(APPOINTMENT_REQ_DATE, NULL, 'N', 'Y')) AS BOOKING_COMPLETE_FLAG
      ,  TO_CHAR(PAD_DF, 'YYYY-MM-DD HH24:MI:SS') AS PAD_DF      
      ,  DELIVERY_TYPE_NAME
      ,  FREIGHT_ROUTE_CODE AS ROUTE_CODE
      ,  PTO_MODEL_FLAG
      ,  PTO_ID
      ,  DISTANCE_USE_FLAG
      ,  LOAD_GROUP_ID      
      ,  SO3_ORDER_TYPE      
      --,  LEGAL_ENTITY_NAME  -- 20151111 BJSONG LGEFS 중복으로 APPEND 부분 제외 
      ,  CUSTOMER_NAME AS GERP_SHIPTO_NAME
      ,  MON
      ,  TUE
      ,  WED
      ,  THU
      ,  FRI
      ,  SAT
      ,  SUN
      ,  TO_CHAR(NVL(SUGGESTED_PLAN_DATE, APPOINTMENT_DATE - NVL(LEAD_TIME, 1)), 'YYYY-MM-DD HH24:MI:SS') AS SUGGESTED_PLAN_DATE
      ,  COLLECTION
      ,  GERP_ORDER_TYPE
      ,  SALESPERSON_NAME
      ,  TO_CHAR(ORDER_APPOINTMENT_FROM_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ORDER_APPOINTMENT_FROM_DATE -- LGEDG 관련 컬럼 추가 20150513 이동현
      ,  TO_CHAR(ORDER_APPOINTMENT_TO_DATE, 'YYYY-MM-DD HH24:MI:SS') AS ORDER_APPOINTMENT_TO_DATE -- LGEDG 관련 컬럼 추가 20150513 이동현 
     -- LGEDG 관련 컬럼 추가 20150421 이동현
    ,XDOCK_CONTAINER  --C20190311_45009 LGEVH 관련 컬럼 추가 20190402 정일현
    ,XDOCK_STATUS --C20190311_45009 LGEVH 관련 컬럼 추가 20190402 정일현
    ,CURRENCY_CODE  --C20200904_97370 CURRENCY CODE 추가
    ,CUSTOMER_PHONE --C20210204_76636 고객 연락처 추가
    ,TO_CHAR(XDOCK_ETA, 'YYYY-MM-DD HH24:MI:SS') AS XDOCK_ETA -- [C20210413_08066 ] XDOCK 관련 컬럼 추가
        ,TO_CHAR(XDOCK_CHANGED_ETA, 'YYYY-MM-DD HH24:MI:SS') AS XDOCK_CHANGED_ETA -- [C20210413_08066 ] XDOCK 관련 컬럼 추가
/*
     ,TO_CHAR(PK_GTM_DATE.GET_DUE_DATE(SHPM_NUM, 'LC', null),'YYYY-MM-DD HH24:MI:SS')    AS LC_BY -- PJ2024A029 ADD 20250929
       ,TO_CHAR(PK_GTM_DATE.GET_DUE_DATE(SHPM_NUM, 'AR', null),'YYYY-MM-DD HH24:MI:SS')    AS AR_BY -- PJ2024A029
       ,TO_CHAR(PK_GTM_DATE.GET_DUE_DATE(SHPM_NUM, 'AC', null),'YYYY-MM-DD HH24:MI:SS')    AS AC_BY -- PJ2024A029
       ,TO_CHAR(PK_GTM_DATE.GET_DUE_DATE(SHPM_NUM, 'TA', null),'YYYY-MM-DD HH24:MI:SS')    AS TA_BY -- PJ2024A029
       ,TO_CHAR(PK_GTM_DATE.GET_DUE_DATE(SHPM_NUM, 'WR', null),'YYYY-MM-DD HH24:MI:SS')    AS WR_BY -- PJ2024A029
       */
       
       /* Due Date RITM2628561*/
       ,(SELECT TO_CHAR(DUE.LOAD_CREATE_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS LC_BY
       ,(SELECT TO_CHAR(DUE.APPOINTMENT_REQUEST_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS AR_BY
       ,(SELECT TO_CHAR(DUE.APPOINTMENT_CONFIRM_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS AC_BY
       ,(SELECT TO_CHAR(DUE.TENDER_RESPONSE_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS TA_BY
       ,(SELECT TO_CHAR(DUE.RELEASE_TO_WH_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS WR_BY
       ,(SELECT TO_CHAR(DUE.SHIP_CONFIRM_DUE,'YYYY-MM-DD HH24:MI:SS') FROM TB_GTM_DUE_DATE_CALC DUE WHERE 1=1 AND DUE.SHIPMENT_NUMBER = SHPM_NUM)     AS SC_BY
    ,TO_CHAR(PK_GTM_DATE.GET_SHPM_DATE(SHPM_NUM, 'APPT_CMPT', null),'YYYY-MM-DD HH24:MI:SS') AS APPOINTMENT_CONFIRM_DATE -- PJ2024A029
    ,TO_CHAR(PK_GTM_DATE.GET_SHPM_DATE(SHPM_NUM, 'ETA', null),'YYYY-MM-DD HH24:MI:SS') AS ETA -- PJ2024A029
    ,PK_LPA_COMMON.GET_GCE_TYPE(SHPM_NUM) AS GCE_TYPE -- PJ2024A029
      FROM (
                SELECT /*+ LEADING(SHPM) INDEX_DESC(SHPM TB_GTM_SHIPMENT_TMS_S_IF_IX20) USE_NL(SHPM CNTR SHIPMENT LEGD IOD MODL LOAD STAT STAT2 ZN SHIPTO) */
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_REQ_DATE FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS APPOINTMENT_REQ_DATE, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_FROM_DATE FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS APPOINTMENT_FROM_DATE, -- C20191106_19648 APPOINTMENT FROM DATE 추가 20191108 정일현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_DATE FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS APPOINTMENT_DATE, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPPOINTMENT_REMARK FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS APPPOINTMENT_REMARK, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_STATUS FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS APPOINTMENT_STATUS, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ ORDER_TYPE FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS BOOKING_HISTORY_ORDER_TYPE, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_NO FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS REFERENCE_NO, -- Hub관련 조건 추가 20150507 이동현
                    ( SELECT /*+index_desc(B TB_GTM_BOOKINGHISTORY_IX04)*/ APPOINTMENT_CONTACT_NAME FROM TB_GTM_BOOKINGHISTORY B WHERE B.SHPM_NUM=LEGD.SHPM_NUM AND B.REG_DATE<=SYSDATE+1 AND NVL(B.SEQ_NUM, 100) = LEGD.SEQ_NUM AND ROWNUM=1 ) AS REQUEST_NAME, -- Hub관련 조건 추가 20150507 이동현
                    SHPM.SHIPMENTNUMBER AS SHPM_NUM,
                    SHPM.SOURCE_HEADER_NO AS GERP_ORDER_NO,
                    SHPM.SHIPMENTDESCRIPTION AS GERP_PICK_NO,
                    SHPM.CUSTOMER_ORDER_NO AS CUSTOMER_ORDER_NO,
                    SHPM.TMS_ORDER_TYPE AS ORDER_TYPE,
                    SHPM.ORI_DELY_TO AS REQUEST_ARRIVAL_DATE,
                    SHPM.SALES_ORDER_DATE AS ORDER_ENTRY_DATE,
                    SHPM.PICK_RELEASE_DATE AS PICK_RELEASE_DATE,
                    LEGD.LD_LEG_ID, 
                    CASE WHEN LEGD.LD_LEG_ID IS NOT NULL THEN (SELECT NAME FROM TMSPROD.CARR_T CARR WHERE LOAD.CARR_CD=CARR.CARR_CD ) ELSE CASE WHEN LEGD.CARR_CMTD_YN = 'T' THEN (SELECT NAME FROM TMSPROD.CARR_T CARR WHERE LEGD.CARR_CD=CARR.CARR_CD ) ELSE NULL END END AS CARR_NAME,
                    CASE WHEN LEGD.LD_LEG_ID IS NOT NULL THEN LOAD.CARR_CD ELSE DECODE(LEGD.CARR_CMTD_YN, 'T', LEGD.CARR_CD, NULL) END AS CARR_CD,
                    CASE WHEN LEGD.LD_LEG_ID IS NOT NULL THEN LOAD.SRVC_CD ELSE DECODE(LEGD.SRVC_CMTD_YN, 'T', LEGD.SRVC_CD, NULL) END AS SRVC_CD,
                    CASE WHEN LEGD.LD_LEG_ID IS NOT NULL THEN LOAD.EQMT_TYP ELSE DECODE(LEGD.EQMT_TYP_CMTD_YN, 'T', LEGD.EQMT_TYP, NULL) END AS EQMT_TYP,
                    LOAD.TRCTR_NUM,
                    LOAD.TRLR_NUM,
                    LOAD.TRCTR_LIC_NUM,
                    LOAD.CRTD_DTT,
                    (SELECT LOAD.RELEASE_TO_WH_DATE FROM TB_GTM_LOAD LOAD WHERE LOAD.LD_LEG_ID = LEGD.LD_LEG_ID AND LOAD.SHIPMENTNUMBER = LEGD.SHPM_NUM) AS RELEASE_TO_WH_DATE, 
                    LOAD.RFRC_NUM1,
                    (SELECT GTMLOAD.SHIPPING_DATE FROM TB_GTM_LOAD GTMLOAD WHERE GTMLOAD.LD_LEG_ID = LEGD.LD_LEG_ID AND GTMLOAD.SHIPMENTNUMBER = LEGD.SHPM_NUM ) AS CFMD_DTT,
                    --LEGD.DROP_ARVL_DTT, -- 20120927
                    IOD.IOD_DATE AS ACTUAL_ARRIVAL_DATE,
                    IOD.IOD_INPUT_DATE AS IOD_INPUT_DATE,
                    IOD.IOD_CONFIRM_FLAG AS IOD_FLAG,
                    CASE WHEN SHIPMENT.CUR_OPTLSTAT_ID = 275 THEN 'Shipment Canceled'
                         WHEN SHIPMENT.CUR_OPTLSTAT_ID <> 275 AND LOAD.LD_LEG_ID IS NULL  THEN 'Unassigned'
                         ELSE STAT.STAT_SHRT_DESC END AS STATUS,
                          STAT2.STAT_SHRT_DESC AS SHIPMENT_STATUS,                         
                    SHPM.BOOKING_NEED_FLAG AS BOOKING_NEED_YN,
                    NVL(LEGD.FRM_SHPG_LOC_NAME,SHIPMENT.FRM_NAME) AS FRM_SHPG_LOC_NAME,
                    NVL(LEGD.TO_SHPG_LOC_NAME,SHIPMENT.TO_NAME) AS TO_SHPG_LOC_NAME,
                    NVL(LEGD.FRM_SHPG_LOC_CD,SHIPMENT.FRM_SHPG_LOC_CD) AS FRM_SHPG_LOC_CD,
                    NVL(LEGD.TO_SHPG_LOC_CD,SHIPMENT.TO_SHPG_LOC_CD) AS TO_SHPG_LOC_CD,
                    NVL(LEGD.TO_STA_CD,SHIPMENT.TO_STA_CD) AS TO_STA_CD,
                    SHPL.GLRGN_ZN_CD AS SHIP_TO_ZONE,
                    NVL(LEGD.TO_CTY_NAME,SHIPMENT.TO_CTY_NAME) AS TO_CTY_NAME,
                    NVL(LEGD.TO_PSTL_CD,SHIPMENT.TO_PSTL_CD) AS TO_PSTL_CD,
                    ( SELECT ADDR.ST_NAME FROM TMSPROD.ADDR_T ADDR WHERE NVL(LEGD.TO_ADDR_ID,SHIPMENT.TO_ADDR_ID)=ADDR.ADDR_ID) AS SHIP_TO_ADDRESS,
                    FC_GTM_GET_PLAN_LEADTIME2(SHPM.SHIPMENTNUMBER) AS LEAD_TIME,
                    MODL.PRODUCT_LEVEL1_CODE AS PL1,
                    MODL.PRODUCT_LEVEL4_CODE AS PL4,
                    MODL.MODEL_CODE AS MODEL_SUFFIX,
                    MODL.MODEL_DESC AS MODEL_DESCRIPTION, 
                    CNTR.MODEL_GRADE AS SUB_INVENTORY_CODE,
                    CNTR.VOLUME AS UNIT_CBM,
                    MODL.GROSS_WEIGHT AS UNIT_WEIGHT,
                    SHPM.TAX_EXCLUSIVE_PRICE AS UNIT_NET_PRICE,
                    ROUND(SHPM.TAX_INCLUSIVE_PRICE - SHPM.TAX_EXCLUSIVE_PRICE, 2) AS TAX_PER_UNIT,
                    ROUND(SHPM.TAX_INCLUSIVE_PRICE, 2) AS UNIT_SELLING_PRICE,
                    CNTR.ORI_QUANTITY,
                    CNTR.RES_QUANTITY AS SHIP_QTY,
                    CASE WHEN LOAD.CUR_OPTLSTAT_ID >= 335 THEN CNTR.RES_QUANTITY ELSE 0 END AS SHIP_CONFIRM_QTY, 
                    NVL(IOD.DELIVERY_QTY,0) AS IRECEIPT_QTY,
                    ( CNTR.RES_QUANTITY * ROUND(CNTR.VOLUME, 4) ) AS TOTAL_CBM,
                    ( CNTR.RES_QUANTITY * MODL.GROSS_WEIGHT ) AS TOTAL_WEIGHT,
                    '' AS FREIGHT_TERM,
                    LEGD.SHPM_ID,
                    LEGD.LD_LEG_DETL_ID,
                    REPLACE(SHPM.PRINTABLEMEMO, ':::', '') AS PICKING_REMARK,
                    SHPM.NONPRINTABLEMEMO AS SHIPPING_REMARK,
                    ZN.ZN_CD AS ZONE,
                    ZN.ZN_DESC AS ZONE_NAME,
                    ZN.SHRT_DESC,
              SHPM.PAD_DF  AS PAD_DF, 
              SHPM.RAD_FROM AS RAD_FROM,
              SHPM.RAD_TO AS RAD_TO,
              SHPM.GERP_SHIPTO_CODE,
              SHPM.DELIVERY_TYPE_NAME,
              SHIPTO.FREIGHT_ROUTE_CODE,
              CNTR.PTO_MODEL_FLAG,
              CNTR.PTO_ID,
              ROUND(LOAD.END_DTT - LOAD.STRD_DTT,2) AS DISTANCE_LEAD_TIME,-- ETA 관련 수정  
                    LT.DISTANCE_USE_FLAG, -- ETA 관련 수정
                    LOAD.RFRC_NUM4 AS LOAD_GROUP_ID,
                    (SELECT CM.CD_NM FROM TB_GTM_CODE_MST CM WHERE CM.CD_TYPE = 'SO3_ORDER_TYPE' AND CM.CD = SHPM.SO3_ORDER_TYPE) AS SO3_ORDER_TYPE
                    ,SHIPTO.CUSTOMER_TYPE,
                    SHPM.LEGAL_ENTITY_NAME,
                    SHIPTO.CUSTOMER_NAME,
                    SUBSTR(SHIPTO.NDD_FLAG, 2, 1) AS MON,
              SUBSTR(SHIPTO.NDD_FLAG, 3, 1) AS TUE,
              SUBSTR(SHIPTO.NDD_FLAG, 4, 1) AS WED,
              SUBSTR(SHIPTO.NDD_FLAG, 5, 1) AS THU,
              SUBSTR(SHIPTO.NDD_FLAG, 6, 1) AS FRI,
              SUBSTR(SHIPTO.NDD_FLAG, 7, 1) AS SAT,
              SUBSTR(SHIPTO.NDD_FLAG, 1, 1) AS SUN,
              SHPM.SUGGESTED_PLAN_DATE,
              DECODE(SHIPD.RECEIPT_REFUSAL_FLAG, 'N', 'Y', 'Y', 'N', '') AS COLLECTION,
              SHIPD.ORDER_TYPE_NAME AS GERP_ORDER_TYPE,
              CNTR.SALESPERSON_NAME
              ,LEGD.SEQ_NUM AS SHIPMENT_LEG -- Hub 관련 컬럼 추가 20150421 이동현
              ,NVL(SHIPTO.SHIPPING_BOOKING_FLAG, 'N') AS SHIPPING_BOOKING_FLAG -- Hub 관련 컬럼 추가 20150421 이동현
              ,(SELECT /*+index_desc(h pk_hub)*/
                    h.name
              FROM tmsprod.hub_t h
             WHERE h.shpg_loc_cd = legd.to_shpg_loc_cd) AS hub -- Hub 관련 컬럼 추가 20150507 이동현
          ,CASE
             WHEN legd.seq_num > 100 THEN
              (SELECT /*+index_desc(ldt fklld_shpm)*/
                      ldt.ld_leg_id
                 FROM tmsprod.ld_leg_detl_t ldt
                WHERE ldt.shpm_id = legd.shpm_id
                  AND ldt.seq_num = (legd.seq_num - 100))
             ELSE
              NULL
           END AS hub_load_id -- Hub 관련 컬럼 추가 20150507 이동현
                    ,DECODE(NVL(SHIPTO.BOOKING_LIST_TYPE, 'N'), 'N','N', 'Y') AS BOOKING_NEED_FLAG_DG -- LGEDG 관련 컬럼 추가 20150510 이동현
                    ,(SELECT O.APPOINTMENT_FROM_DATE
                        FROM TB_GTM_ORDERS_GERP_R_IF  O
                       WHERE O.INTERFACE_ID = SHPM.GERP_IF_ID) AS ORDER_APPOINTMENT_FROM_DATE -- LGEDG 관련 컬럼 추가 20150513 이동현
                    ,(SELECT O.APPOINTMENT_TO_DATE
                        FROM TB_GTM_ORDERS_GERP_R_IF  O
                       WHERE O.INTERFACE_ID = SHPM.GERP_IF_ID) AS ORDER_APPOINTMENT_TO_DATE -- LGEDG 관련 컬럼 추가 20150513 이동현
                    ,(SELECT CM.CD_NM FROM TB_GTM_CODE_MST CM
             WHERE CM.CD_TYPE = 'BOOKING_METHOD'
               AND CM.CD = SHIPTO.BOOKING_METHOD) AS BOOKING_METHOD -- LGEDG 관련 컬럼 추가 20150625 이동현
                    ,SHIPTO.BOOKING_LIST_TYPE -- LGEDG 관련 컬럼 추가 20150513 이동현
                    ,SHIPTO.EMAIL_ADDRESS -- LGEDG 관련 컬럼 추가 20150513 이동현
                    ,(SELECT OD.ATTRIBUTE8 FROM TB_GTM_ORDERS_GERP_R_IF OD WHERE OD.MOVE_ORDER_LINE_ID = SHPM.MOVE_ORDER_LINE_ID AND OD.LEGAL_ENTITY_NAME = SHPM.LEGAL_ENTITY_NAME AND OD.TMS_PRCS_FLAG = 'Y') AS EMAIL_ADDRESS2 --C20210604_30847 - OBS 고객 이메일 관련 변경 20210611
                    ,SHIPD.SHIP_TO_SHORT_NAME -- LGEDG 관련 컬럼 추가 20150615 이동현
                    ,(SELECT max(OD.CUSTOMER_MODEL_CODE) FROM TB_GTM_ORDERS_GERP_R_IF OD WHERE OD.MOVE_ORDER_LINE_ID = SHPM.MOVE_ORDER_LINE_ID AND OD.LEGAL_ENTITY_NAME = SHPM.LEGAL_ENTITY_NAME AND OD.TMS_PRCS_FLAG = 'Y') AS CUSTOMER_MODEL_CODE
                    ,LOAD.RFRC_NUM6    AS PALLET_QTY  --LGEFS 20151111 BJSONG  PALLET QTY ADD 
              ,LOAD.RFRC_NUM7    AS LINEAR_METER --LGEFS 관련 컬럼 추가 20151209  BJSONG  LINEAR METER
                    ,(SELECT max(OD.SHIPPING_METHOD_CODE) FROM TB_GTM_ORDERS_GERP_R_IF OD WHERE OD.MOVE_ORDER_LINE_ID = SHPM.MOVE_ORDER_LINE_ID AND OD.LEGAL_ENTITY_NAME = SHPM.LEGAL_ENTITY_NAME AND OD.TMS_PRCS_FLAG = 'Y') AS SHIPPING_METHOD  --LGEFS 20151111 BJSONG SHIPPING_METHOD_CODE ADD
                    ,DECODE(NVL(SHIPD.RAD_FLAG, 'N'), 'Y', 'N', 'Y') AS RAD_FLAG -- [C20160325_20827] 컬럼 추가.
                    ,FC_GTM_GET_GERP_LINE_NO(SHPM.SHIPMENTNUMBER) AS GERP_ORDER_LINE_NO --[C20171213_55962] Add Column                    
                -- LGEDG 관련 컬럼 추가 20150421 이동현
              ,SHPM.CO_NUMBER AS XDOCK_CONTAINER --C20190311_45009 LGEVH 관련 컬럼 추가 20190402 정일현
              ,DECODE(CNTR.MODEL_GRADE,'GS-XDOCK',DECODE(SHPM.XDOCK_STATUS,'OPEN','CONFIRMED',SHPM.XDOCK_STATUS),'OPEN') AS XDOCK_STATUS --C20190311_45009 LGEVH 관련 컬럼 추가 20190402 정일현
              ,(SELECT max(OD.CURRENCY_CODE) FROM TB_GTM_ORDERS_GERP_R_IF OD WHERE OD.MOVE_ORDER_LINE_ID = SHPM.MOVE_ORDER_LINE_ID AND OD.LEGAL_ENTITY_NAME = SHPM.LEGAL_ENTITY_NAME) AS CURRENCY_CODE  --C20200904_97370 CURRENCY CODE 추가
              ,(SELECT NVL(NVL(O.CONSIGNEE_PHONE1_NO,O.CONSIGNEE_PHONE2_NO),O.SHIP_TO_PHONE_NO)
                        FROM TB_GTM_ORDERS_GERP_R_IF  O
                       WHERE O.INTERFACE_ID = SHPM.GERP_IF_ID) AS CUSTOMER_PHONE --C20210204_76636 고객 연락처 추가
                    ,TO_DATE(SHIPD.ATTRIBUTE01, 'YYYYMMDDHH24MISS') AS XDOCK_ETA -- [C20210413_08066 ]  XDOCK 관련 컬럼 추가
                ,TO_DATE(SHIPD.ATTRIBUTE02, 'YYYYMMDDHH24MISS') AS XDOCK_CHANGED_ETA -- [C20210413_08066 ] XDOCK 관련 컬럼 추가
              FROM TB_GTM_SHIPMENT_TMS_S_IF SHPM,
                TB_GTM_CONTAINER_TMS_S_IF CNTR,
                TMSPROD.SHIPMENT_R SHIPMENT,
                TMSPROD.LD_LEG_DETL_T LEGD,
                TB_GTM_IOD IOD,
                TB_GTM_MODEL MODL,
                TMSPROD.SHPG_LOC_T SHPL,
                TMSPROD.LD_LEG_T LOAD,
                TMSPROD.STATUS_R STAT,
                TMSPROD.STATUS_R STAT2,
                TMSPROD.ZN_T              ZN,
                TB_GTM_SHIPTO SHIPTO,
                TB_GTM_SERVICE_LEADTIME LT,  -- ETA 관련 수정
                TB_GTM_SHIPMENT_DETAIL SHIPD    
              WHERE SHPM.SHIPMENTNUMBER = CNTR.SHIPMENTNUMBER
                AND SHPM.SHIPMENTNUMBER = SHIPMENT.SHPM_NUM
                AND SHPM.SHIPMENTNUMBER = LEGD.SHPM_NUM(+)
                AND LEGD.LD_LEG_ID = IOD.LD_LEG_ID(+)
                AND LEGD.SHPM_NUM = IOD.SHIPMENTNUMBER(+)
                AND CNTR.AFFILIATE_CODE = MODL.AFFILIATE_CODE
                AND CNTR.CONTAINERTYPECODE = MODL.MODEL_CODE
                AND NVL(LEGD.TO_SHPG_LOC_CD,SHIPMENT.TO_SHPG_LOC_CD) = SHPL.SHPG_LOC_CD
                AND NVL(LEGD.TO_PNT_TYP_ENU, 2) = SHPL.SHPG_LOC_TYP_ENU  -- 조건 추가 20150522 이동현  -- 조건 추가 20150522 이동현
                AND SHPL.SHPG_LOC_TYP_ENU IN (2, 3, 4)
                AND LEGD.LD_LEG_ID = LOAD.LD_LEG_ID(+)
                AND LOAD.CUR_OPTLSTAT_ID = STAT.STAT_ID(+)
                AND SHIPMENT.CUR_OPTLSTAT_ID = STAT2.STAT_ID
                AND SHPM.ZONE_CODE = ZN.ZN_CD(+)
                AND SHPM.GERP_SHIPTO_CODE =  SHIPTO.CUSTOMER_NO(+)
                AND SHPM.LEGAL_ENTITY_NAME =  SHIPTO.LEGAL_ENTITY_NAME(+)
                AND LOAD.DIV_CD = LT.DIV_CD(+) -- ETA 관련 수정
                AND LOAD.SRVC_CD = LT.SERVICE_CODE(+) -- ETA 관련 수정
                AND SHPM.SHIPMENTNUMBER = SHIPD.SHIPMENTNUMBER
                
              
          AND SHPM.SYSTEMPLANID= '400101'--Plan Id 
          AND SHPM.PICK_RELEASE_DATE BETWEEN TO_DATE('20260402','YYYYMMDD') AND TO_DATE('20260409','YYYYMMDD') + 0.99999 
          
          
          
          
          
          
          
          
          
          
          
          
          
          AND NVL(LEGD.FRM_SHPG_LOC_CD,SHIPMENT.FRM_SHPG_LOC_CD) IN ( 'N2U' ) 
          
          
          
          
          
          AND ( NVL(SHIPTO.CUSTOMER_TYPE,'N/A') IN ( 'BK' , 'BS'  , 'FX'  , 'FD'  , 'RT'  , 'SD'  , 'N/A'  ) -- Ship To (FILTER)
                OR SHIPTO.CUSTOMER_TYPE IS NULL  ) 
          AND LEGD.SEQ_NUM IN ( 100 ) 
          AND (CASE WHEN SHIPMENT.CUR_OPTLSTAT_ID = 275 THEN 275
                         WHEN SHIPMENT.CUR_OPTLSTAT_ID <> 275 AND LOAD.LD_LEG_ID IS NULL  THEN 280
                         ELSE STAT.STAT_ID END ) IN  ( '280' ) 
          -- C20161010_88234 SHIP TO CODE 조회조건 추가 20161118 원송연
          
          --C20190311_45009 X Dock Container No 추가 20190402 정일현
          --C20190311_45009 X Dock Mapping Status 추가 20190402 정일현
          --C20190311_45009 Subinventory 추가 20190402 정일현
          --RITM2158184 Multi Pick No 조건 추가 2025.05.21 정일현
      ) AA
      WHERE 1=1
      
      
      
      
      AND ( APPOINTMENT_STATUS IN ( 'CANCEL' , 'CMPT'  , 'DELAY'  , 'HOLD'  , 'NR'  , 'REQD'  , 'SC'  , 'N/A'  ) -- Ship To (FILTER)
                OR APPOINTMENT_STATUS IS NULL  ) 
      
      
      
      --order by SHPM_NUM DESC, SHIPMENT_LEG
      
      
      ) inner_temp where rownum <= ('0'+1) * '100'
) where devonindex between  '1' and '1'+99 
