SELECT 
A.DELIVERY_NO
,A.PICK_ORDER_NO
,A.PICK_SEQ_NO
,A.SOURCE_HEADER_NO
,TRANSACTION_DATE
,APPOINTMENT_FROM_DATE
,APPOINTMENT_TO_DATE
,A.DRIVER_NAME
,TRUCK_NO
,CONTAINER_NO
,ATTRIBUTE37
,ATTRIBUTE38
,A.APIGW_TRANSFER_FLAG
,A.APIGW_TRANSFER_DATE
FROM TB_GTM_SHPCFM_GERP_S_IF A
WHERE 1=1
AND A.CREATION_DATE  >SYSDATE-0.8
